
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g @angular/cli
    ng add @angular/pwa
    ng build --prod
  displayName: 'npm install and build'
