
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
    npm install -g @angular/cli --skip-confirmation
    ng add @angular/pwa --skip-confirmation
    ng build --prod
  displayName: 'npm install and build'
