
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd .
    npm install --legacy-peer-deps --force
    npm install -g @angular/cli --skip-confirmation --force
    npm i @angular/service-worker@17.0.2 --skip-confirmation --force
    ng add @angular/pwa --skip-confirmation --force
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)'
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
